apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hostpath-per-pod-flex-volume-deploy
spec:
  template:
    metadata:
      name: hostpath-per-pod-flex-volume-deploy
      labels:
        app: hostpath-per-pod-flex-volume-deploy
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/tencentyun/hostpathperpod:latest
          name: deploy
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec